In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib

Using matplotlib backend: <object object at 0x127f75690>


In [3]:
# read in all the words
words = open('names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [4]:
words

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn',
 'abigail',
 'emily',
 'elizabeth',
 'mila',
 'ella',
 'avery',
 'sofia',
 'camila',
 'aria',
 'scarlett',
 'victoria',
 'madison',
 'luna',
 'grace',
 'chloe',
 'penelope',
 'layla',
 'riley',
 'zoey',
 'nora',
 'lily',
 'eleanor',
 'hannah',
 'lillian',
 'addison',
 'aubrey',
 'ellie',
 'stella',
 'natalie',
 'zoe',
 'leah',
 'hazel',
 'violet',
 'aurora',
 'savannah',
 'audrey',
 'brooklyn',
 'bella',
 'claire',
 'skylar',
 'lucy',
 'paisley',
 'everly',
 'anna',
 'caroline',
 'nova',
 'genesis',
 'emilia',
 'kennedy',
 'samantha',
 'maya',
 'willow',
 'kinsley',
 'naomi',
 'aaliyah',
 'elena',
 'sarah',
 'ariana',
 'allison',
 'gabriella',
 'alice',
 'madelyn',
 'cora',
 'ruby',
 'eva',
 'serenity',
 'autumn',
 'adeline',
 'hailey',
 'gianna',
 'valentina',
 'isla',
 'eliana',
 'quinn',
 'nevaeh',
 'ivy',
 'sadie',
 'piper',
 'lydia',
 'alexa',
 'josephine',
 'emery',
 'julia'

In [5]:
len(words)

32033

In [9]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}

In [10]:
print(stoi)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '.': 0}


In [11]:
print(itos)

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [12]:
# build the dataset

block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words[:5]:
    
    print(w)
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        print(''.join(itos[i] for i in context), '--->', itos[ix])
        context = context[1:] + [ix]
        
X = torch.tensor(X)
Y = torch.tensor(Y)

emma
... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
olivia
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
ava
... ---> a
..a ---> v
.av ---> a
ava ---> .
isabella
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
sophia
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [13]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [14]:
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [15]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [19]:
C = torch.randn((27, 2))

In [20]:
C[5]

tensor([-0.1311, -0.9357])

In [22]:
F.one_hot(torch.tensor(5), num_classes=27)

tensor([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0])

In [23]:
F.one_hot(torch.tensor(5), num_classes=27).shape

torch.Size([27])

In [25]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C

tensor([-0.1311, -0.9357])

In [27]:
C[[5, 6, 7]]

tensor([[-0.1311, -0.9357],
        [ 0.8420,  0.7559],
        [-0.2744, -0.2975]])

In [28]:
C[X]

tensor([[[ 1.2411, -1.0596],
         [ 1.2411, -1.0596],
         [ 1.2411, -1.0596]],

        [[ 1.2411, -1.0596],
         [ 1.2411, -1.0596],
         [-0.1311, -0.9357]],

        [[ 1.2411, -1.0596],
         [-0.1311, -0.9357],
         [-0.5348, -0.2689]],

        [[-0.1311, -0.9357],
         [-0.5348, -0.2689],
         [-0.5348, -0.2689]],

        [[-0.5348, -0.2689],
         [-0.5348, -0.2689],
         [-1.0086,  1.0135]],

        [[ 1.2411, -1.0596],
         [ 1.2411, -1.0596],
         [ 1.2411, -1.0596]],

        [[ 1.2411, -1.0596],
         [ 1.2411, -1.0596],
         [ 1.6100,  1.1950]],

        [[ 1.2411, -1.0596],
         [ 1.6100,  1.1950],
         [ 2.5583,  2.1507]],

        [[ 1.6100,  1.1950],
         [ 2.5583,  2.1507],
         [-0.0417, -0.1173]],

        [[ 2.5583,  2.1507],
         [-0.0417, -0.1173],
         [-0.3928, -0.6215]],

        [[-0.0417, -0.1173],
         [-0.3928, -0.6215],
         [-0.0417, -0.1173]],

        [[-0.3928, -0

In [29]:
emb = C[X]
emb.shape

torch.Size([32, 3, 2])

In [30]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [31]:
emb @ W1 + b1

RuntimeError: mat1 and mat2 shapes cannot be multiplied (96x2 and 6x100)

In [32]:
emb[:, 0, :].shape

torch.Size([32, 2])

In [33]:
emb[:, 1, :].shape

torch.Size([32, 2])

In [34]:
emb[:, 2, :].shape

torch.Size([32, 2])

In [35]:
emb[:, 2, :]

tensor([[ 1.2411, -1.0596],
        [-0.1311, -0.9357],
        [-0.5348, -0.2689],
        [-0.5348, -0.2689],
        [-1.0086,  1.0135],
        [ 1.2411, -1.0596],
        [ 1.6100,  1.1950],
        [ 2.5583,  2.1507],
        [-0.0417, -0.1173],
        [-0.3928, -0.6215],
        [-0.0417, -0.1173],
        [-1.0086,  1.0135],
        [ 1.2411, -1.0596],
        [-1.0086,  1.0135],
        [-0.3928, -0.6215],
        [-1.0086,  1.0135],
        [ 1.2411, -1.0596],
        [-0.0417, -0.1173],
        [ 0.6790,  0.0244],
        [-1.0086,  1.0135],
        [-0.1155, -0.9991],
        [-0.1311, -0.9357],
        [ 2.5583,  2.1507],
        [ 2.5583,  2.1507],
        [-1.0086,  1.0135],
        [ 1.2411, -1.0596],
        [ 0.6790,  0.0244],
        [ 1.6100,  1.1950],
        [ 0.4152, -0.5119],
        [-0.9087,  1.4072],
        [-0.0417, -0.1173],
        [-1.0086,  1.0135]])

In [36]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]],)

tensor([[ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [-0.1311, -0.9357],
        [-0.5348, -0.2689],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.6100,  1.1950],
        [ 2.5583,  2.1507],
        [-0.0417, -0.1173],
        [-0.3928, -0.6215],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [-1.0086,  1.0135],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [-0.0417, -0.1173],
        [ 0.6790,  0.0244],
        [-1.0086,  1.0135],
        [-0.1155, -0.9991],
        [-0.1311, -0.9357],
        [ 2.5583,  2.1507],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [ 0.6790,  0.0244],
        [ 1.6100,  1.1950],
        [ 0.4152, -0.5119],
        [-0.9087,  1.4072],
        [ 1.2411, -1.0596],
        [ 1.2411, -1.0596],
        [-0.1311, -0.9357],
        [-0.5348, -0

In [38]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]],).shape

torch.Size([96, 2])

In [37]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1)

tensor([[ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -0.1311, -0.9357],
        [ 1.2411, -1.0596, -0.1311, -0.9357, -0.5348, -0.2689],
        [-0.1311, -0.9357, -0.5348, -0.2689, -0.5348, -0.2689],
        [-0.5348, -0.2689, -0.5348, -0.2689, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.6100,  1.1950],
        [ 1.2411, -1.0596,  1.6100,  1.1950,  2.5583,  2.1507],
        [ 1.6100,  1.1950,  2.5583,  2.1507, -0.0417, -0.1173],
        [ 2.5583,  2.1507, -0.0417, -0.1173, -0.3928, -0.6215],
        [-0.0417, -0.1173, -0.3928, -0.6215, -0.0417, -0.1173],
        [-0.3928, -0.6215, -0.0417, -0.1173, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -1.0086,  1.0135],
        [ 1.2411, -1.0596, -1.0086,  1.0135, -0.3928, -0.6215],
        [-1.0086,  1.0135, -0.3928, -0.6

In [39]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1).shape

torch.Size([32, 6])

In [41]:
len(torch.unbind(emb, 1))

3

In [42]:
torch.cat(torch.unbind(emb, 1), 1)

tensor([[ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -0.1311, -0.9357],
        [ 1.2411, -1.0596, -0.1311, -0.9357, -0.5348, -0.2689],
        [-0.1311, -0.9357, -0.5348, -0.2689, -0.5348, -0.2689],
        [-0.5348, -0.2689, -0.5348, -0.2689, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.6100,  1.1950],
        [ 1.2411, -1.0596,  1.6100,  1.1950,  2.5583,  2.1507],
        [ 1.6100,  1.1950,  2.5583,  2.1507, -0.0417, -0.1173],
        [ 2.5583,  2.1507, -0.0417, -0.1173, -0.3928, -0.6215],
        [-0.0417, -0.1173, -0.3928, -0.6215, -0.0417, -0.1173],
        [-0.3928, -0.6215, -0.0417, -0.1173, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -1.0086,  1.0135],
        [ 1.2411, -1.0596, -1.0086,  1.0135, -0.3928, -0.6215],
        [-1.0086,  1.0135, -0.3928, -0.6

In [43]:
torch.cat(torch.unbind(emb, 1), 1).shape

torch.Size([32, 6])

In [45]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [46]:
a.shape

torch.Size([18])

In [47]:
a.view(3, 3, 2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [48]:
a.storage()

/var/folders/69/ncrrlk1j7510dx967flbkwmc0000gn/T/ipykernel_1274/214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [49]:
emb.shape

torch.Size([32, 3, 2])

In [50]:
emb.view(32, 6)

tensor([[ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -0.1311, -0.9357],
        [ 1.2411, -1.0596, -0.1311, -0.9357, -0.5348, -0.2689],
        [-0.1311, -0.9357, -0.5348, -0.2689, -0.5348, -0.2689],
        [-0.5348, -0.2689, -0.5348, -0.2689, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.6100,  1.1950],
        [ 1.2411, -1.0596,  1.6100,  1.1950,  2.5583,  2.1507],
        [ 1.6100,  1.1950,  2.5583,  2.1507, -0.0417, -0.1173],
        [ 2.5583,  2.1507, -0.0417, -0.1173, -0.3928, -0.6215],
        [-0.0417, -0.1173, -0.3928, -0.6215, -0.0417, -0.1173],
        [-0.3928, -0.6215, -0.0417, -0.1173, -1.0086,  1.0135],
        [ 1.2411, -1.0596,  1.2411, -1.0596,  1.2411, -1.0596],
        [ 1.2411, -1.0596,  1.2411, -1.0596, -1.0086,  1.0135],
        [ 1.2411, -1.0596, -1.0086,  1.0135, -0.3928, -0.6215],
        [-1.0086,  1.0135, -0.3928, -0.6

In [51]:
emb.view(32, 6) == torch.cat(torch.unbind(emb, 1), 1)

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, T

In [52]:
h = emb.view(32, 6) @ W1 + b1

In [56]:
h = torch.tanh(emb.view(emb.shape[0], 6) @ W1 + b1)

In [57]:
h.shape

torch.Size([32, 100])

In [58]:
(emb.view(-1, 6) @ W1).shape

torch.Size([32, 100])

In [59]:
b1.shape

torch.Size([100])

In [60]:
# 32, 100
#  1, 100

In [61]:
W2 = torch.randn((100, 27))
b2 = torch.randn(27)

In [62]:
logits = h @ W2 + b2

In [63]:
logits.shape

torch.Size([32, 27])

In [64]:
counts = logits.exp()

In [69]:
prob = counts / counts.sum(1, keepdims=True)

In [70]:
prob.shape

torch.Size([32, 27])

In [72]:
torch.arange(32)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [67]:
Y

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [73]:
loss = -prob[torch.arange(32), Y].log().mean() 
loss

tensor(18.4641)

In [74]:
# ----------

In [75]:
X.shape, Y.shape

(torch.Size([32, 3]), torch.Size([32]))

In [76]:
g = torch.Generator().manual_seed(2147483647)
C = torch.randn((27, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 27), generator=g)
b2 = torch.randn(27, generator=g)
parameters = [C, W1, b1, W2, b2]

In [77]:
sum(p.nelement() for p in parameters) # number of parameters in total

3481

In [78]:
emb = C[X]
h = torch.tanh(emb.view(-1, 6) @ W1 + b1) # (32, 100)
logits = h @ W2 + b2 # (32, 27)
counts = logits.exp()
prob = counts / counts.sum(1, keepdims=True)
loss = -prob[torch.arange(32), Y].log().mean()
loss

tensor(17.7697)

In [79]:
F.cross_entropy(logits, Y)

tensor(17.7697)

In [80]:
loss = F.cross_entropy(logits, Y)

In [84]:
logits = torch.tensor([-100, -3, 0 , 100])
counts = logits.exp()
prob = counts / counts.sum() # 1, keepdims=True)
prob

tensor([0., 0., 0., nan])

In [85]:
counts

tensor([3.7835e-44, 4.9787e-02, 1.0000e+00,        inf])